# Generated by Django 2.1.5 on 2020-04-01 16:06

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer_zayavki', models.IntegerField(unique=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('fio_klienta', models.CharField(default='', max_length=100)),
                ('summa_zayavki', models.IntegerField()),
                ('purpose', models.CharField(max_length=200)),
                ('srok_kredita', models.IntegerField()),
                ('product', models.CharField(max_length=20)),
                ('zalog', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('istochnik', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=200, null=True)),
                ('date_refuse', models.DateTimeField(null=True)),
                ('protokol_number', models.CharField(max_length=20, null=True, unique=True)),
                ('credit_user', models.ForeignKey(on_delete=models.SET('Удаленный пользователь'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
