# Generated by Django 2.1.5 on 2020-04-08 06:36

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='credit_user',
            field=models.ForeignKey(on_delete=models.SET('Удаленный пользователь'), to=settings.AUTH_USER_MODEL, verbose_name='Кредитный специалист'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заявки'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_refuse',
            field=models.DateTimeField(null=True, verbose_name='Дата отказа/одобрения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fio_klienta',
            field=models.CharField(max_length=100, verbose_name='ФИО клиента/Наименование компании'),
        ),
        migrations.AlterField(
            model_name='client',
            name='istochnik',
            field=models.CharField(max_length=20, verbose_name='Источник погашения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nomer_zayavki',
            field=models.IntegerField(unique=True, verbose_name='Номер заявки'),
        ),
        migrations.AlterField(
            model_name='client',
            name='product',
            field=models.CharField(max_length=20, verbose_name='Наименование продукта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='protokol_number',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Номер протокола'),
        ),
        migrations.AlterField(
            model_name='client',
            name='purpose',
            field=models.CharField(max_length=200, verbose_name='Цель кредита'),
        ),
        migrations.AlterField(
            model_name='client',
            name='reason',
            field=models.CharField(max_length=200, null=True, verbose_name='Причина отказа/Условия одобрения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='srok_kredita',
            field=models.IntegerField(verbose_name='Срок кредита'),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='client',
            name='summa_zayavki',
            field=models.IntegerField(verbose_name='Сумма заявки'),
        ),
        migrations.AlterField(
            model_name='client',
            name='zalog',
            field=models.CharField(max_length=20, verbose_name='Обеспечение'),
        ),
    ]
