# Generated by Django 2.1.5 on 2020-04-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20200408_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_refuse',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отказа/одобрения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='protokol_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Номер протокола'),
        ),
        migrations.AlterField(
            model_name='client',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Причина отказа/Условия одобрения'),
        ),
    ]
