# Generated by Django 2.1.5 on 2020-04-15 12:27

from django.db import migrations, models
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20200415_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='credit_user',
            field=models.ForeignKey(on_delete=models.SET('Удаленный пользователь'), to='users.Officer', verbose_name='Кредитный специалист'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_refuse',
            field=models.DateTimeField(blank=True, default=journal.models.one_day_more, null=True, verbose_name='Дата отказа/одобрения'),
        ),
    ]
