# Generated by Django 2.1.5 on 2020-04-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20200415_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('На рассмотрении', 'На рассмотрении'), ('Одобрено', 'Одобрено'), ('Отказано', 'Отказано')], max_length=20, verbose_name='Статус'),
        ),
    ]
