# Generated by Django 2.1.5 on 2020-04-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_auto_20200415_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nomer_zayavki',
            field=models.IntegerField(unique=True, verbose_name='Номер заявки'),
        ),
    ]
