# Generated by Django 2.1.5 on 2020-04-18 14:40

from django.db import migrations, models
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_auto_20200418_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nomer_zayavki',
            field=models.IntegerField(default=journal.models.next_number, unique=True, verbose_name='Номер заявки'),
        ),
    ]
