# Generated by Django 2.1.5 on 2020-04-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_auto_20200418_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Продукт кредитования')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='product',
            field=models.ForeignKey(on_delete=models.SET('Удаленный продукт'), to='journal.Product', verbose_name='Наименование продукта'),
        ),
    ]
