# Generated by Django 2.1.5 on 2020-10-16 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_auto_20200421_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата заявки'),
        ),
        migrations.AlterField(
            model_name='client',
            name='istochnik',
            field=models.CharField(choices=[('Заработная плата', 'Заработная плата'), ('Доход от бизнеса', 'Доход от бизнеса'), ('Другие доходы', 'Другие доходы')], max_length=20, verbose_name='Источник погашения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='purpose',
            field=models.CharField(choices=[('Потребительские', 'Потребительские'), ('Бизнес', 'Бизнес')], max_length=200, verbose_name='Цель кредита'),
        ),
        migrations.AlterField(
            model_name='client',
            name='zalog',
            field=models.CharField(choices=[('Заработная плата', 'Заработная плата'), ('Доход от бизнеса', 'Доход от бизнеса'), ('Поручительство', 'Поручительство'), ('Недвижимость', 'Недвижимость'), ('Движимое имущество', 'Движимое имущество')], max_length=20, verbose_name='Обеспечение'),
        ),
    ]
