# Generated by Django 2.1.5 on 2020-10-16 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_auto_20201016_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заявки'),
        ),
    ]
