# Generated by Django 2.1.5 on 2020-12-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_auto_20201016_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='interest_rate',
            field=models.FloatField(default=28, verbose_name='Процентная ставка'),
        ),
        migrations.AddField(
            model_name='product',
            name='interest_rate_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Процентная ставка вторая'),
        ),
        migrations.AddField(
            model_name='product',
            name='interest_rate_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Процентная ставка третья'),
        ),
        migrations.AddField(
            model_name='product',
            name='sum',
            field=models.IntegerField(default=100000, verbose_name='Сумма 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='sum_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сумма 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='sum_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сумма 1'),
        ),
    ]
