# Generated by Django 2.1.5 on 2020-12-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_auto_20201202_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sum_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сумма 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sum_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сумма 3'),
        ),
    ]
