# Generated by Django 2.1.5 on 2020-12-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0013_auto_20201202_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commission',
            field=models.FloatField(default=0, verbose_name='Комиссия за выдачу'),
        ),
        migrations.AddField(
            model_name='product',
            name='commission_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Комиссия за выдачу 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='commission_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Комиссия за выдачу 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='commission_cash',
            field=models.FloatField(default=0, verbose_name='Коммиссия за обналичивание'),
        ),
    ]
