# Generated by Django 2.1.5 on 2021-09-20 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210920_1338'),
        ('journal', '0014_auto_20201202_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Office', verbose_name='Офис'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='nomer_zayavki',
            field=models.IntegerField(unique=True, verbose_name='Номер заявки'),
        ),
    ]
