# Generated by Django 2.1.5 on 2021-09-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210920_1338'),
        ('journal', '0015_auto_20210920_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nomer_zayavki',
            field=models.IntegerField(verbose_name='Номер заявки'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('office', 'nomer_zayavki')},
        ),
    ]
