# Generated by Django 2.1.5 on 2020-04-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='name_short',
            field=models.CharField(default='name', max_length=20, verbose_name='ФИО сотрудника (коротко)'),
            preserve_default=False,
        ),
    ]
