# Generated by Django 2.1.5 on 2020-04-08 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_officer_name_short'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='name_short',
        ),
    ]
