# Generated by Django 2.1.5 on 2021-09-20 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_officer_name_short'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('office_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Идентификатор офиса')),
                ('office_name', models.CharField(max_length=255, verbose_name='Наименование офиса')),
            ],
        ),
        migrations.AddField(
            model_name='officer',
            name='office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Office', verbose_name='Офис'),
            preserve_default=False,
        ),
    ]
